name: StatsCalculusPyPact

dependencies:
  - python=3.7
  - jupyter==1.0.0
  - pandas==0.25.1
  - numpy==1.17.2
  - scipy==1.3.1
  - matplotlib==3.1.1
  - seaborn==0.9.0
  - scikit-learn==0.21.3
  - statsmodels==0.11.1
  - pip
  - pip:
    - .